//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafedraApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public Cycle()
        {
            this.Subjects = new HashSet<Subject>();
        }
    
        public int CycleId { get; set; }
        public string CycleCode { get; set; }
    
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
