//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafedraApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.StudyPlans = new HashSet<StudyPlan>();
        }
    
        public int SubjectId { get; set; }
        public string SubjectName { get; set; }
        public int Hours { get; set; }
    
        public virtual Cycle Cycle { get; set; }
        public virtual ICollection<StudyPlan> StudyPlans { get; set; }
    }
}
