//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafedraApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTeacherLoad
    {
        public int StudyPlanId { get; set; }
        public string FIO { get; set; }
        public string SubjectName { get; set; }
        public string CycleCode { get; set; }
        public int Hours { get; set; }
    }
}
